version: '3.8'

services:
  # MCP-Only Deployment (Backend + Gateway Only)
  notion-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.mcp-only
    container_name: notion-mcp-server-mcp
    ports:
      - "${GATEWAY_PORT:-3001}:3001"
      - "${MCP_PORT:-8080}:8080"
    environment:
      - NODE_ENV=production
      - GATEWAY_PORT=3001
      - MCP_PORT=8080
      - NOTION_TOKEN=${NOTION_TOKEN:-demo}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID:-demo}
      - NOTION_CHARACTERS_DB_ID=${NOTION_CHARACTERS_DB_ID:-demo}
      - NOTION_SCENES_DB_ID=${NOTION_SCENES_DB_ID:-demo}
      - NOTION_LOCATIONS_DB_ID=${NOTION_LOCATIONS_DB_ID:-demo}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/usr/src/app/logs  # For logging (optional)
    networks:
      - mcp-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mcp-gateway.rule=Host(`${MCP_DOMAIN:-localhost}`)"
      - "traefik.http.services.mcp-gateway.loadbalancer.server.port=3001"

  # Redis for caching (optional but recommended for production)
  redis:
    image: redis:7-alpine
    container_name: notion-mcp-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - mcp-network
    restart: unless-stopped

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: notion-mcp-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro  # SSL certificates
    networks:
      - mcp-network
    depends_on:
      - notion-mcp-server
    restart: unless-stopped
    profiles:
      - "with-proxy"

volumes:
  redis-data:
    driver: local

networks:
  mcp-network:
    driver: bridge