[build]
builder = "nixpacks"
buildCommand = "npm ci --omit=dev && cd backend && npm ci --omit=dev"

[deploy]
startCommand = "node backend/server/app.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[environments.production]
NODE_ENV = "production"

# Required Environment Variables (จะต้องตั้งใน Railway Dashboard)
# NOTION_TOKEN
# NOTION_CHARACTERS_DB_ID  
# NOTION_SCENES_DB_ID
# NOTION_PROJECTS_DB_ID
# NOTION_TASKS_DB_ID
# GEMINI_API_KEY
