name: 'Pull from Notion'

on:
  # ทำให้เราสามารถกดปุ่ม "Run workflow" ในหน้า Actions ของ GitHub ได้
  workflow_dispatch:
    inputs:
      database_id:
        description: 'Notion Database ID (optional - will use default from secrets)'
        required: false
        default: ''
      target_folder:
        description: 'Target folder for synced files'
        required: false
        default: 'vault'

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 'Install dependencies'
        run: npm ci

      - name: 'Create vault directory if not exists'
        run: mkdir -p vault

      - name: 'Run Notion Pull Script'
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_ID: ${{ github.event.inputs.database_id || secrets.NOTION_CHARACTERS_DB_ID }}
          TARGET_FOLDER: ${{ github.event.inputs.target_folder || 'vault' }}
          GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
        run: node ./scripts/pull-from-notion.js

      - name: 'Commit and push changes'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add vault/
          # ตรวจสอบว่ามีอะไรเปลี่ยนแปลงก่อน commit
          if ! git diff --staged --quiet; then
            git commit -m "🔄 Sync: Pull content from Notion database"
            git push
          else
            echo "✅ No changes detected - vault is up to date"
          fi
